config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'home#index'
  get 'about' => 'home#about'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(name: :asc).page(params[:page])
    # .all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: t('contact_created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: t('contact_updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('contact_erased') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :nickname, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact, :html => {class:'form-horizontal' } do |f| %>

  <% if @contact.errors.any? %>
    <div class='alert alert-danger' role='alert'>
      <h2><%= pluralize(@contact.errors.count, "error") %> t('form_save_error'):</h2>
      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name, t('name'),class:"col-sm-3 control-label"  %>
    <div class='col-sm-9'>
      <%= f.text_field :name, class:'form-control', required:true %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :nickname, t('nickname'),class:"col-sm-3 control-label" %>
    <div class='col-sm-9'>
      <%= f.text_field :nickname, class:'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :email, t('email_address'),class:"col-sm-3 control-label"  %>
    <div class='col-sm-9'>
      <%= f.text_field :email, class:'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-sm-9 col-sm-offset-3'>
      <%= f.submit class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1><%= t('editing_contact') %></h1>
<%= render 'form' %>

app/views/contacts/index.html.erb
<div class='alert'><%= notice %></div>
<h1><%= t('my_contacts') %> <%=
  link_to ('<span class="glyphicon glyphicon-plus"></span>').html_safe, new_contact_path, class:"btn btn-success btn-md"
%></h1>
<%
  # recupera o número de registros na base de dados
  line=@contacts.count
%>
<% unless @contacts.empty? %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th><%= t('name') %></th>
        <th><%= t('nickname') %></th>
        <th><%= t('email_address') %></th>
        <th><%= t('actions') %></th>
        </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.nickname || '- - -' %></td>
        <td><%= contact.email || '- - -' %></td>
        <td><%= link_to ('<span class="glyphicon glyphicon-eye-open"></span>').html_safe, contact, class:"btn btn-info btn-xs" %> <%=
                link_to ('<span class="glyphicon glyphicon-pencil"></span>').html_safe, edit_contact_path(contact), class:"btn btn-primary btn-xs" %> <%=
                link_to ('<span class="glyphicon glyphicon-trash"></span>').html_safe, contact, method: :delete, data: { confirm: t('are_you_sure?') }, class: "btn btn-danger btn-xs" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @contacts %>
  <div class='alert'>
    <%= t('total_of') %> <%= line %> <% if line==1 %><%= t('contact') %><% else %><%= t('contacts') %><% end %>
  </div>
<% else %>
  <div class="alert alert-warning" role="alert">
    <strong><%= t('alert') =%></strong> : <%= t('no_contacts_yet') %>!
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1><%= t('new_contact') %></h1>
<%= render 'form' %>

app/views/contacts/show.html.erb
<div class='alert'><%= notice %></div>
<h1><%= @contact.name %> <%=
link_to ('<span class="glyphicon glyphicon-pencil"></span>').html_safe, edit_contact_path(@contact), class:"btn btn-primary btn-md" %></h1>
<p><strong><%= t('nickname') %></strong> : <%= @contact.nickname || '---' %></p>
<p><strong><%= t('email_address') %></strong> : <%= @contact.email || '---' %></p>
<div class='alert alert-info'>
  <%= t('created_at') %>: <em><%= @contact.created_at %></em> -- <%= t('updated_at') %>: <em><%= @contact.updated_at %></em>
</div>

app/views/home/_footer.html.erb
<footer class='text-center footer'>
    Para maiores informações ou contato, acesse meu blog em <a href='http://giovannireisnunes.wordpress.com' target='_BLANK'>giovannireisnunes.wordpress.com</a>.
</footer>

app/views/home/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><=% t('toggle_navigation') %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('app_title'), root_path, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      <li><%= link_to t('nav_new'), new_contact_path %></li>
      <li><%= link_to t('nav_contacts'), contacts_path %></li>
      <li><%= link_to t('nav_about'), about_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1><%= t('about') %></h1>
<div class='well'>
  <div class="media">
    <div class="media-left media-top">
      <a href="#">
        <img class="media-object" src="AM_logo_128x128.png" alt="AM"/>
      </a>
    </div>
    <div class="media-body">
      <h2 class="media-heading"><%= t('app_title') %></h2>
      <p><em><%= t('app_description') =%></p>
      <p>Esta é uma aplicação simples escrita em <a href='http://rubyonrails.org/'>Ruby
      on Rails</a> e criada com o propósito de servir como um exemplo razoavelmente documentado
      de como é programar neste <em>framework</em>. Além do próprio <strong>Rails</strong>
      foram também utilizados o <em>framework</em> <strong>Bootstrap</strong> para a geração
      do HTML e CSS, o <strong>Atom</strong> para a edição e o <strong>Git</strong> para o
      controle de versão no código.</p>
      <p>O processo de desenvolvimento pode ser acompanhado nas seguintes publicações:</p>
      <ul>
      <%
        #
        # isto aqui não é bonito mas facilita a vida caso eu crie uma 4ª ou 5ª partes
        #
        posts=[ 'giovannireisnunes.wordpress.com/2016/04/22/exemplo-em-rails-parte-1/',
                'giovannireisnunes.wordpress.com/2016/05/13/exemplo-em-rails-parte-2/',
                'giovannireisnunes.wordpress.com/2016/05/20/exemplo-em-rails-parte-3/' ]
        parte=0
      %>
      <% posts.each do |post| %>
        <li><a href='<%= "https://#{post}" %>' target='_blank'>Exemplo em Rails, parte <%= parte+=1 %></a></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class='jumbotron'>
    <h1><%= t('app_title') %></h1>
    <p><%= t('app_description') %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AM</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'home/navigation.html.erb' %>
  <div class='container'>
    <%= yield %>
  </div>
  <hr/>
  <%= render 'home/footer.html.erb' %>
  </body>
</html>